global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'order_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8080']
        labels:
          application: 'Order Service Application'

  - job_name: 'user_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8080']
        labels:
          application: 'User Service Application'

  - job_name: 'book_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['book-service:8080']
        labels:
          application: 'Book Service Application'
